secure: "QrhNWrS/nyBZKsydo2exbMSp2huBaCkRBAt0hWTYoY+9pSfbbNa9OD2elsRWUi1RztK9oiubxK3KoHOGOP3L6N4CiRJ2zIX4Z25OkDagphdeAXTAtAPG6as3+ucz/Ujl8shEvHuhrUeeuKvtNsVJQ0b0DHIDRXkzizDg7yWJiNk="

language: r
warnings_are_errors: true
sudo: required
r_binary_packages:
  - jsonlite
  - devtools
  - httr
  - crayon
  - htmltools
  - lazyeval
  - testthat
r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
